# Site settings
title: Luke Carbis
url: "http://carb.is" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
email: luke@carb.is
email_encoded: "yhxr@pneo.vf" # see http://rot13.com
name: Luke Carbis
position: WordPress Engineer
company: WP Stream
company_url: http://wp-stream.com/
portfolio:
  -
    title: GitHub
    url: http://github.com/lukecarbis
  -
    title: WordPress
    url: http://profiles.wordpress.org/lukecarbis
  -
    title: Photos
    url: http://luketakesphotos.wordpress.com/
social:
  -
    title: Ello
    url: https://ello.co/lukecarbis
  -
    title: Twitter
    url: http://twitter.com/lukecarbis
  -
    title: Skype
    url: skype:lukecarbis?call

# Build settings
markdown: kramdown
