# Site settings
title: Luke Carbis
url: "http://carb.is" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
who: Luke Carbis
what: WordPress engineer
where: Queensland, Australia
email: luke@carb.is
email_encoded: "yhxr@pneo.vf" # see http://rot13.com

work:
  - "Lead development and product design for [WP Stream](https://wp-stream.com)."
  - "WordPress Engineer at [XWP](http://xwp.co), for [WordPress.com VIP](https://vip.wordpress.com)."
  - "WordPress Meetup organiser for the [Sunshine Coast WordPress meetup](https://wpsc.co)."
  - "Office work for [Bridges for Peace](http://bridgesforpeace.com) (volunteer)."

# Build settings
markdown: kramdown
