# Site settings
title: Luke Carbis
url: "http://carb.is" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
who: Luke Carbis
what: WordPress developer
where: Queensland, Australia
email: luke@carb.is
email_encoded: "yhxr@pneo.vf" # see http://rot13.com

work:
  - "Product Manager for [XWP](http://xwp.co)."
  - "Lead developer for [Stream](https://wp-stream.com)."
  - "National Zealous8:2 Coordinator for [Bridges for Peace](http://bridgesforpeace.com) (volunteer)."
  - "Organiser for [WordPress Sunshine Coast](http://wpsc.co), speaker at WordCamp [Sydney](http://sydney.wordcamp.org/2014/) and [Wellington](http://wellington.wordcamp.org/2014/)."

# Build settings
markdown: kramdown
