# Site settings
title: Luke Carbis
url: "http://carb.is" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
who: Luke Carbis
what: WordPress developer
where: Queensland, Australia
email: luke@carb.is
email_encoded: "yhxr@pneo.vf" # see http://rot13.com

work:
  - "Lead developer at [WP Stream](https://wp-stream.com)."
  - "Product Manager at [XWP](http://xwp.co)."
  - "National Zealous8:2 Coordinator at [Bridges for Peace](http://bridgesforpeace.com) (volunteer)."
  - "Meetup organiser for the [Sunshine Coast WordPress meetup](http://wpsc.co)."
  - "Speaker at WordCamps [Sydney](http://sydney.wordcamp.org/2014/) and [Wellington](http://wellington.wordcamp.org/2014/)."

# Build settings
markdown: kramdown
